apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: roboshop-ebs-sc
  resources:
    requests:
      storage: 4Gi
--- 

apiVersion: v1
kind: Pod
metadata:
  name: nginx 
  labels: 
    purpose: ebs-dymanic
spec:
  containers:
  - name: nginx 
    image: nginx
    volumeMounts:
    - name: ebs-dymanic-claim
      mountPath: /usr/share/nginx/html 
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: ebs-dynamic
---
apiVersion: v1 
kind: Service
metadata:
  name: nginx-ebs-dymanic
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dymanic
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80
      nodePort: 30007
