
# It is also created by admins
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: roboshop-ebs-sc
reclaimPolicy: Retain
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer