apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop
  labels: 
    project: roboshop
    createdBy: phani
    environment: dev
spec:
  containers:
  - name: nginx-phani
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
  - name: almalinux
    image: almalinux
  - name: nginx-siva
    image: nginx