apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: roboshop
  labels: 
    project: roboshop
    createdBy: phani
    environment: dev
spec:
  containers:
  - name: nginx-phani
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: mysql
    image: mysql
    command: ["sleep", "1000"]
    ports:
    - containerPort: 3306

 