apiVersion: v1
kind: Pod 
metadata:
  name: multi-container-pod
  labels:
    purpose: multi-container
spec:
  containers:
  - name: nginx-1
    image: nginx
  - name: nginx-2
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]
