apiVersion: v1 
kind: Pod 
metadata:
  name: frontend
spec:
  containers: 
  - name: nginx
    image: nginx
    env:
      - name: "COURSE_NAME"
        value: "Kubernetes"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "100Mi"
        cpu: "500m"