apiVersion: v1
kind: Pod
metadata:
  name: service-demo
  labels:   # these labels are same as service selector to register
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx