apiVersion: v1 
kind: Pod
metadata:
  name: loadbalancer-service-demo
  labels:
    project: roboshop
    component: frontend
    environment: dev
    purpose: loadbalancer 
spec:
  containers:
  - name: nginx
    image: nginx